apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: demo-grafana-stack
  labels:
    app: demo-grafana-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-grafana-stack
  template:
    metadata:
      labels:
        app: demo-grafana-stack
    spec:
      containers:
        - name: demo-grafana-stack
          image: namnh123/demo-grafana-stack-arm64v8
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-grafana-stack
  namespace: app
spec:
  selector:
    app: demo-grafana-stack
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
