apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: '15.7.1'
    helm:
      valueFiles:
      - $values/projects/kube-prometheus-stack/prometheus-values.yaml
  - repoURL: https://github.com/nguyenhoangnam123/demo-grafana-stacks.git
    targetRevision: main
    ref: values
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: 'https://grafana.github.io/helm-charts/'
      chart: grafana
      targetRevision: '6.58.4'
      helm:
        valueFiles:
          - $values/projects/kube-prometheus-stack/grafana-values.yaml
    - repoURL: https://github.com/nguyenhoangnam123/demo-grafana-stacks.git
      targetRevision: main
      ref: values
